apiVersion: v1
kind: Secret
metadata:
  name: phoneshop-env
  namespace: phoneshop
type: Opaque
stringData:
  .env: |
    DB_HOST=your-rds-endpoint.amazonaws.com
    DB_USER=admin
    DB_PASSWORD=replace-me
    DB_NAME=PhoneShop
    DB_PORT=3306
    PORT=3000
    HOST=0.0.0.0
